framework: nextjs16
boilerplate_url: "https://github.com/sabuj0338/nextjs-light-boilerplate.git"
package_manager: "pnpm"
planner_rules:
  - "rules/planning_rules_summary.md"
coder_rules:
  - "./rules/AI_AGENT_RULES.md"
  - "./rules/nextjs-project-setup-guide-light.md"
dependencies:
  ui:
    - shadcn
    - tailwindcss
    - lucide-react

  state:
    - zustand
    - react-query

  forms:
    - react-hook-form
    - zod

rules:
  - never_edit_shadcn_ui
  - use_react_query_for_api
  - use_zustand_only_for_ui
  - follow_folder_structure
  # translation rules (i18next)
  - must_add_text_into_translation_file
  - update_component_to_work_with_translation_file

  # css rules
  - use_tailwind_css
